// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TODO: Replace these with your actual Supabase project credentials
const SUPABASE_URL = "https://oemwaoaebmwdfrndohmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbXdhb2FlYm13ZGZybmRvaG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzQ2NDgsImV4cCI6MjA1OTI1MDY0OH0.KuPNahbiyWtJbWfLpo96ojHDJ-IY4l_kB842-H35J2E";

// No env check needed when hardcoding


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
